// 团队成员数据
// AIDING团队信息（智核团队）

// 团队基金信息
const fundingData = [
    {
        id: "nsfc",
        name: "National Natural Science Foundation of China",
        nameCn: "国家自然科学基金",
        grantNo: "12575189",
        fullText: "the National Natural Science Foundation of China (Grant No. 12575189)",
        fullTextCn: "国家自然科学基金 (批准号: 12575189)"
    },
    {
        id: "basic_research",
        name: "Basic Research and Stable Support Research Project of Science and Technology Industry Bureau of China",
        nameCn: "国家基础性科研院所基础科研稳定支持专项",
        grantNo: "WDZC-2023050305",
        fullText: "the Basic Research and Stable Support Research Project of Science and Technology Industry Bureau of China (Grant No. WDZC-2023050305)",
        fullTextCn: "国家基础性科研院所基础科研稳定支持专项 (批准号: WDZC-2023-05-03-05)"
    },
    {
        id: "sichuan_tech",
        name: "Sichuan Science and Technology Program",
        nameCn: "四川省揭榜挂帅行业共性技术攻关项目",
        grantNo: "2023YFG0373",
        fullText: "the Supported by Sichuan Science and Technology Program (Grant Nos. 2023YFG0373)",
        fullTextCn: "四川省揭榜挂帅行业共性技术攻关项目 (批准号: 2023YFG0373)"
    }
];

// 团队成员数据
const teamMembers = [
    {
        id: "liudong",
        name: "刘东",
        englishName: "Dong Liu",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "高性能数值计算、工业软件开发、智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["liudong@npic.ac.cn", "liudong@uestc.edu.cn"],
        phones: ["13980956120"],
        orcid: "0009-0002-4768-9039",
        avatar: "../assets/avatar/liudong.jpg",
        position: "团队负责人"
    },
    {
        id: "xule",
        name: "徐乐",
        englishName: "Le Xu",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["lxu_tju@outlook.com"],
        phones: ["18482129886"],
        orcid: "",
        avatar: "../assets/avatar/xule.jpg",
        position: "合作成员"
    },
    {
        id: "liuyang",
        name: "刘洋",
        englishName: "Yang Liu",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、人工智能、分数阶PDE",
        institution: "四川大学计算机学院（软件学院、人工智能学院），中国成都 610065",
        institutionEn: "College of Computer Science (School of Software and School of Artificial Intelligence), Sichuan University, Chengdu 610065, China",
        address: "四川省成都市武侯区一环路南一段24号",
        addressEn: "No. 24, Section 1, South 1st Ring Road, Wuhou District, Chengdu, Sichuan Province, China",
        emails: ["mathliuyang@163.com", "liuyang@stu.sicnu.edu.cn"],
        phones: ["19522123213"],
        orcid: "0000-0001-7668-3467",
        avatar: "../assets/avatar/liuyang.jpg",
        position: "核心成员"
    },
    {
        id: "liaozhen",
        name: "廖真",
        englishName: "Zhen Liao",
        gender: "女",
        degree: "博士",
        title: "工程师",
        researchFields: "高性能计算、人工智能、智能科学计算",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["npicliaozhen@163.com"],
        phones: ["19180770226"],
        orcid: "",
        avatar: "../assets/avatar/liaozhen.jpg",
        position: "核心成员"
    },
    {
        id: "jiangyong",
        name: "江勇",
        englishName: "Yong Jiang",
        gender: "男",
        degree: "硕士",
        title: "工程师",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["1135228970@qq.com"],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/jiangyong.jpg",
        position: "核心成员"
    },
    {
        id: "wangjunfeng",
        name: "王俊峰",
        englishName: "Junfeng Wang",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "网络安全",
        institution: "四川大学计算机学院（软件学院、人工智能学院），中国成都 610065",
        institutionEn: "College of Computer Science (School of Software and School of Artificial Intelligence), Sichuan University, Chengdu 610065, China",
        address: "四川省成都市武侯区一环路南一段24号",
        addressEn: "No. 24, Section 1, South 1st Ring Road, Wuhou District, Chengdu, Sichuan Province, China",
        emails: ["wangjf@scu.edu.cn"],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/wangjunfeng.jpg",
        position: "合作成员"
    },
    {
        id: "luomaokang",
        name: "罗懋康",
        englishName: "Maokang Luo",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "",
        institution: "四川大学数学学院，中国成都 610065",
        institutionEn: "School of Mathematics, Sichuan University, Chengdu 610065, China;",
        address: "四川省成都市武侯区一环路南一段24号",
        addressEn: "No. 24, Section 1, South 1st Ring Road, Wuhou District, Chengdu, Sichuan Province, China",
        emails: ["makaluo@scu.edu.cn"],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/luomaokang.jpg",
        position: "合作成员"
    },
    {
        id: "wangfei",
        name: "王飞",
        englishName: "Fei Wang",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "智能科学计算、人工智能、计算数学",
        institution: "西安交通大学数学与统计学院，中国西安 710049",
        institutionEn: "School of Mathematics and Statistics, Xi'an Jiaotong University, Xi'an 710049, China",
        address: "陕西省西安市咸宁西路28号",
        addressEn: "No. 28, West Xianning Road, Xi'an, Shaanxi Province, China",
        emails: ["feiwang.xjtu@xjtu.edu.cn"],
        phones: ["13119131365"],
        orcid: "",
        avatar: "../assets/avatar/wangfei.jpg",
        position: "合作成员"
    },
    {
        id: "danghaoning",
        name: "党浩宁",
        englishName: "Haoning Dang",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、有限差分、计算数学",
        institution: "西安交通大学数学与统计学院，中国西安 710049",
        institutionEn: "School of Mathematics and Statistics, Xi'an Jiaotong University, Xi'an 710049, China",
        address: "陕西省西安市咸宁西路28号",
        addressEn: "No. 28, West Xianning Road, Xi'an, Shaanxi Province, China",
        emails: ["haoningdang.xjtu@stu.xjtu.edu.cn"],
        phones: ["18340619868"],
        orcid: "",
        avatar: "../assets/avatar/danghaoning.jpg",
        position: "合作成员"
    },
    {
        id: "wangkai",
        name: "王凯",
        englishName: "Kai Wang",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "",
        institution: "浙江大学物理学院，浙江近代物理中心，中国杭州 310058",
        institutionEn: "Zhejiang Institute of Modern Physics, School of Physics, Zhejiang University, Hangzhou 310058, China",
        address: "浙江省杭州市西湖区余杭塘路866号",
        addressEn: "No. 866, Yuhangtang Road, Xihu District, Hangzhou, Zhejiang Province, China",
        emails: ["wangkai1@zju.edu.cn"],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/wangkai.jpg",
        position: "合作成员"
    },
    {
        id: "liuzhouyu",
        name: "刘宙宇",
        englishName: "Zhouyu Liu",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "核反应堆物理、蒙特卡洛方法",
        institution: "西安交通大学能源与动力工程学院，中国西安 710049",
        institutionEn: "School of Energy and Power Engineering, Xi'an Jiaotong University, Xi'an 710049, China",
        address: "陕西省西安市咸宁西路28号",
        addressEn: "No. 28, West Xianning Road, Xi'an, Shaanxi Province, China",
        emails: ["zhouyuliu@xjtu.edu.cn"],
        phones: ["17791978005"],
        orcid: "",
        avatar: "../assets/avatar/liuzhouyu.jpg",
        position: "合作成员"
    },
    {
        id: "zhangbin",
        name: "张斌",
        englishName: "Bin Zhang",
        gender: "男",
        degree: "博士",
        title: "工程师",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["jsszwtzb@163.com"],
        phones: ["13551191758"],
        orcid: "",
        avatar: "../assets/avatar/zhangbin.jpg",
        position: "合作成员"
    },
    {
        id: "wuchao",
        name: "吴超",
        englishName: "Chao Wu",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["22031110387@stu.xidian.edu.cn"],
        phones: ["18894330931"],
        orcid: "",
        avatar: "../assets/avatar/wuchao.jpg",
        position: "核心成员"
    },
    {
        id: "zhangjinchao",
        name: "张晋超",
        englishName: "Jinchao Zhang",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "",
        institution: "哈尔滨工程大学，核安全与仿真技术国防重点学科实验室，中国哈尔滨 150001",
        institutionEn: "Fundamental Science on Nuclear Safety and Simulation Technology Laboratory, Harbin Engineering University, Harbin, 150001, China",
        address: "黑龙江省哈尔滨市南岗区南通大街145号",
        addressEn: "No. 145, Nantong Street, Nangang District, Harbin, Heilongjiang Province, China",
        emails: ["13935397912@hrbeu.edu.cn"],
        phones: ["13935397912"],
        orcid: "",
        avatar: "../assets/avatar/zhangjinchao.jpg",
        position: "合作成员"
    },
    {
        id: "liuqingkai",
        name: "刘青凯",
        englishName: "Qingkai Liu",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "计算机科学与技术",
        institution: "北京应用物理与计算数学研究所，中国北京  100094",
        institutionEn: " Institute of Applied Physics and Computational Mathematics, Beijing 100094, China",
        address: "北京市海淀区丰豪东路2号",
        addressEn: "No. 2, Fenghao East Road, Haidian District, Beijing, Beijing, China",
        emails: ["liuqk@iapcm.ac.cn"],
        phones: ["13621058267"],
        orcid: "",
        avatar: "../assets/avatar/liuqingkai.jpg",
        position: "合作成员"
    },
    {
        id: "chenqilong",
        name: "陈奇隆",
        englishName: "Qilong Chen",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["894860272@qq.com"],
        phones: ["19980816294"],
        orcid: "",
        avatar: "../assets/avatar/chenqilong.jpg",
        position: "核心成员"
    },
    {
        id: "zhangqian",
        name: "张乾",
        englishName: "Qian Zhang",
        gender: "男",
        degree: "博士",
        title: "工程师",
        researchFields: "",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["zhangqian0515@zju.edu.cn"],
        phones: ["17604664028"],
        orcid: "",
        avatar: "../assets/avatar/zhangqian.jpg",
        position: "合作成员"
    },
    {
        id: "hekangjun",
        name: "贺康俊",
        englishName: "Kangjun He",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["820982892@qq.com"],
        phones: ["18382350304"],
        orcid: "",
        avatar: "../assets/avatar/hekangjun.jpg",
        position: "核心成员"
    },
    {
        id: "liuzhengu",
        name: "刘贞谷",
        englishName: "Zhenyu Liu",
        gender: "男",
        degree: "博士",
        title: "工程师",
        researchFields: "智能科学计算、人工智能、断裂力学",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["zhenyuliuchn@foxmail.com"],
        phones: ["17828093154"],
        orcid: "",
        avatar: "../assets/avatar/liuzhenyu.jpg",
        position: "核心成员"
    },
    {
        id: "zhaochen",
        name: "赵晨",
        englishName: "Chen Zhao",
        gender: "男",
        degree: "博士",
        title: "工程师",
        researchFields: "",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["zhaochen@npic.ac.cn"],
        phones: ["15680832829"],
        orcid: "",
        avatar: "../assets/avatar/zhaochen.jpg",
        position: "合作成员"
    },
    {
        id: "renzhiyuan",
        name: "任志愿",
        englishName: "Zhiyuan Ren",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: ["renzhiyuan@uestc.edu.cn"],
        phones: [],
        orcid: "0009-0005-5682-787X",
        avatar: "../assets/avatar/renzhiyuan.jpg",
        position: "核心成员"
    },
    {
        id: "fengziliang",
        name: "冯子亮",
        englishName: "Ziliang Feng",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "",
        institution: "四川大学计算机学院（软件学院、人工智能学院），中国成都 610065",
        institutionEn: "College of Computer Science (School of Software and School of Artificial Intelligence), Sichuan University, Chengdu 610065, China",
        address: "四川省成都市武侯区一环路南一段24号",
        addressEn: "No. 24, Section 1, South 1st Ring Road, Wuhou District, Chengdu, Sichuan Province, China",
        emails: ["fengziliang@scu.edu.cn"],
        phones: ["13982101801"],
        orcid: "",
        avatar: "../assets/avatar/fengziliang.jpg",
        position: "合作成员"
    },
    {
        id: "zhaixiyan",
        name: "翟西岩",
        englishName: "Xiyan Zhai",
        gender: "男",
        degree: "硕士",
        title: "",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: [],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/zhaixiyan.jpg",
        position: "核心成员"
    },
    {
        id: "zhangzhenyuan",
        name: "张真源",
        englishName: "Zhenyuan Zhang",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: [],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/zhangzhenyuan.jpg",
        position: "核心成员"
    },
    {
        id: "dengli",
        name: "邓力",
        englishName: "Li Deng",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "",
        institution: "北京应用物理与计算数学研究所，中国工程物理研究院，中国北京 100094",
        institutionEn: "Institute of Applied Physics and Computational Mathematics, China Academy of Engineering Physics, Beijing 100094, China",
        address: "北京市海淀区丰豪东路2号",
        addressEn: "No. 2, Fenghao East Road, Haidian District, Beijing, China",
        emails: ["deng_li@iapcm.ac.cn"],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/dengli.jpg",
        position: "合作成员"
    },
    {
        id: "duanzhouhang",
        name: "段州航",
        englishName: "Zhouhang Duan",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: [],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/duanzhouhang.jpg",
        position: "核心成员"
    },
    {
        id: "wangxueqiang",
        name: "王雪强",
        englishName: "Xueqiang Wang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: [],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/wangxueqiang.jpg",
        position: "核心成员"
    },
    {
        id: "yucaiyang",
        name: "俞蔡阳",
        englishName: "Caiyang Yu",
        gender: "男",
        degree: "博士",
        title: "",
        researchFields: "",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        address: "四川省成都市双流区长顺大道一段328号",
        addressEn: "No. 328, Section 1, Changshun Avenue, Shuangliu District, Chengdu, Sichuan Province, China",
        emails: [],
        phones: [],
        orcid: "",
        avatar: "../assets/avatar/yucaiyang.jpg",
        position: "核心成员"
    }
];

// 导出数据供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { teamMembers, fundingData };
} else {
    window.teamMembers = teamMembers;
    window.fundingData = fundingData;
}