// 团队成员数据
// AIDING团队信息（智核团队）

// 团队基金信息
const fundingData = [
    {
        id: "nsfc",
        name: "National Natural Science Foundation of China",
        nameCn: "国家自然科学基金",
        grantNo: "12575189",
        fullText: "the National Natural Science Foundation of China (Grant No. 12575189)",
        fullTextCn: "国家自然科学基金 (批准号: 12575189)"
    },
    {
        id: "basic_research",
        name: "Basic Research and Stable Support Research Project of Science and Technology Industry Bureau of China",
        nameCn: "国防科技工业局基础研究与稳定支持科研项目",
        grantNo: "WDZC-2023050305",
        fullText: "the Basic Research and Stable Support Research Project of Science and Technology Industry Bureau of China (Grant No. WDZC-2023050305)",
        fullTextCn: "国防科技工业局基础研究与稳定支持科研项目 (批准号: WDZC-2023050305)"
    },
    {
        id: "sichuan_tech",
        name: "Sichuan Science and Technology Program",
        nameCn: "四川省科技计划项目",
        grantNo: "2023YFG0373",
        fullText: "the Supported by Sichuan Science and Technology Program (Grant Nos. 2023YFG0373)",
        fullTextCn: "四川省科技计划项目 (批准号: 2023YFG0373)"
    }
];

// 团队成员数据
const teamMembers = [
    {
        id: "liudong",
        name: "刘东",
        englishName: "Dong Liu",
        gender: "男",
        degree: "博士",
        title: "教授",
        researchFields: "高性能数值计算、工业软件开发、智能科学计算、人工智能",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["liudong@uestc.edu.cn"],
        phones: ["13980956120"],
        orcid: "0009-0002-4768-9039",
        avatar: "https://example.com/avatar/liudong.jpg", // 可替换为实际头像链接
        position: "团队负责人"
    },
    {
        id: "wangkai",
        name: "王凯",
        englishName: "Kai Wang",
        gender: "男",
        degree: "博士",
        title: "副教授",
        researchFields: "数值模拟、计算流体力学、多物理场耦合",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["wangkai@example.com"],
        phones: ["13812345678"],
        orcid: "0000-0002-1234-5678",
        avatar: "https://example.com/avatar/wangkai.jpg",
        position: "核心成员"
    },
    {
        id: "wangfei",
        name: "王飞",
        englishName: "Fei Wang",
        gender: "男",
        degree: "博士",
        title: "副教授",
        researchFields: "机器学习、数据挖掘、智能算法",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["wangfei@example.com"],
        phones: ["13987654321"],
        orcid: "0000-0002-2345-6789",
        avatar: "https://example.com/avatar/wangfei.jpg",
        position: "核心成员"
    },
    {
        id: "liuzhouyu",
        name: "刘宙宇",
        englishName: "Zhouyu Liu",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "并行计算、高性能计算、分布式系统",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["liuzhouyu@example.com"],
        phones: ["13611111111"],
        orcid: "0000-0002-3456-7890",
        avatar: "https://example.com/avatar/liuzhouyu.jpg",
        position: "研究成员"
    },
    {
        id: "danghaoning",
        name: "党浩宁",
        englishName: "Haoning Dang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "计算机图形学、可视化、人机交互",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["danghaoning@example.com"],
        phones: ["13722222222"],
        orcid: "0000-0002-4567-8901",
        avatar: "https://example.com/avatar/danghaoning.jpg",
        position: "研究成员"
    },
    {
        id: "wangjunfeng",
        name: "王俊峰",
        englishName: "Junfeng Wang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "软件工程、代码优化、系统架构",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["wangjunfeng@example.com"],
        phones: ["13833333333"],
        orcid: "0000-0002-5678-9012",
        avatar: "https://example.com/avatar/wangjunfeng.jpg",
        position: "研究成员"
    },
    {
        id: "zhangbin",
        name: "张斌",
        englishName: "Bin Zhang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "算法设计、数据结构、优化理论",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["zhangbin@example.com"],
        phones: ["13944444444"],
        orcid: "0000-0002-6789-0123",
        avatar: "https://example.com/avatar/zhangbin.jpg",
        position: "研究成员"
    },
    {
        id: "xule",
        name: "徐乐",
        englishName: "Le Xu",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "人工智能、深度学习、计算机视觉",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["xule@example.com"],
        phones: ["13655555555"],
        orcid: "0000-0002-7890-1234",
        avatar: "https://example.com/avatar/xule.jpg",
        position: "研究成员"
    },
    {
        id: "luomaokang",
        name: "罗懋康",
        englishName: "Maokang Luo",
        gender: "男",
        degree: "博士",
        title: "副教授",
        researchFields: "数值分析、偏微分方程、科学计算",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["luomaokang@example.com"],
        phones: ["13766666666"],
        orcid: "0000-0002-8901-2345",
        avatar: "https://example.com/avatar/luomaokang.jpg",
        position: "核心成员"
    },
    {
        id: "fengziliang",
        name: "冯子亮",
        englishName: "Ziliang Feng",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "云计算、大数据处理、分布式存储",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["fengziliang@example.com"],
        phones: ["13877777777"],
        orcid: "0000-0002-9012-3456",
        avatar: "https://example.com/avatar/fengziliang.jpg",
        position: "研究成员"
    },
    {
        id: "zhangjinchao",
        name: "张晋超",
        englishName: "Jinchao Zhang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "网络安全、密码学、信息安全",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["zhangjinchao@example.com"],
        phones: ["13988888888"],
        orcid: "0000-0002-0123-4567",
        avatar: "https://example.com/avatar/zhangjinchao.jpg",
        position: "研究成员"
    },
    {
        id: "zhangqian",
        name: "张乾",
        englishName: "Qian Zhang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "量子计算、量子算法、量子信息",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["zhangqian@example.com"],
        phones: ["13699999999"],
        orcid: "0000-0002-1234-5678",
        avatar: "https://example.com/avatar/zhangqian.jpg",
        position: "研究成员"
    },
    {
        id: "zhaochen",
        name: "赵晨",
        englishName: "Chen Zhao",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "自然语言处理、知识图谱、信息检索",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["zhaochen@example.com"],
        phones: ["13700000000"],
        orcid: "0000-0002-2345-6789",
        avatar: "https://example.com/avatar/zhaochen.jpg",
        position: "研究成员"
    },
    {
        id: "liuzhengu",
        name: "刘贞谷",
        englishName: "Zhengu Liu",
        gender: "男",
        degree: "博士",
        title: "副教授",
        researchFields: "机器人学、控制理论、自动化",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["liuzhengu@example.com"],
        phones: ["13811111111"],
        orcid: "0000-0002-3456-7890",
        avatar: "https://example.com/avatar/liuzhengu.jpg",
        position: "核心成员"
    },
    {
        id: "liaozhen",
        name: "廖真",
        englishName: "Zhen Liao",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "数据库系统、数据管理、信息检索",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["liaozhen@example.com"],
        phones: ["13922222222"],
        orcid: "0000-0002-4567-8901",
        avatar: "https://example.com/avatar/liaozhen.jpg",
        position: "研究成员"
    },
    {
        id: "wuchao",
        name: "吴超",
        englishName: "Chao Wu",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "嵌入式系统、物联网、边缘计算",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["wuchao@example.com"],
        phones: ["13633333333"],
        orcid: "0000-0002-5678-9012",
        avatar: "https://example.com/avatar/wuchao.jpg",
        position: "研究成员"
    },
    {
        id: "liuyang",
        name: "刘洋",
        englishName: "Yang Liu",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "计算机视觉、图像处理、模式识别",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["liuyang@example.com"],
        phones: ["13744444444"],
        orcid: "0000-0002-6789-0123",
        avatar: "../assets/cover/Science/001/001.jpg",
        position: "研究成员"
    },
    {
        id: "chenqilong",
        name: "陈奇隆",
        englishName: "Qilong Chen",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "区块链、分布式账本、智能合约",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["chenqilong@example.com"],
        phones: ["13855555555"],
        orcid: "0000-0002-7890-1234",
        avatar: "https://example.com/avatar/chenqilong.jpg",
        position: "研究成员"
    },
    {
        id: "jiangyong",
        name: "江勇",
        englishName: "Yong Jiang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "操作系统、内核开发、系统性能优化",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["jiangyong@example.com"],
        phones: ["13966666666"],
        orcid: "0000-0002-8901-2345",
        avatar: "https://example.com/avatar/jiangyong.jpg",
        position: "研究成员"
    },
    {
        id: "hekangjun",
        name: "贺康俊",
        englishName: "Kangjun He",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "人机交互、用户体验、界面设计",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["hekangjun@example.com"],
        phones: ["13677777777"],
        orcid: "0000-0002-9012-3456",
        avatar: "https://example.com/avatar/hekangjun.jpg",
        position: "研究成员"
    },
    {
        id: "renzhiyuan",
        name: "任志愿",
        englishName: "Zhiyuan Ren",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "生物信息学、计算生物学、基因组学",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["renzhiyuan@example.com"],
        phones: ["13888888888"],
        orcid: "0000-0002-0123-4567",
        avatar: "https://example.com/avatar/renzhiyuan.jpg",
        position: "研究成员"
    },
    {
        id: "zhaixiyan",
        name: "翟西岩",
        englishName: "Xiyan Zhai",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "计算语言学、语音识别、自然语言理解",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["zhaixiyan@example.com"],
        phones: ["13999999999"],
        orcid: "0000-0002-1234-5678",
        avatar: "https://example.com/avatar/zhaixiyan.jpg",
        position: "研究成员"
    },
    {
        id: "zhangzhenyuan",
        name: "张真源",
        englishName: "Zhenyuan Zhang",
        gender: "男",
        degree: "博士",
        title: "讲师",
        researchFields: "虚拟现实、增强现实、混合现实",
        institution: "中国核动力研究院，先进核能技术国家重点实验室，中国成都 610213",
        institutionEn: "Nuclear Power Institute of China, State Key Laboratory of Advanced Nuclear Energy Technology, Chengdu 610213, China",
        emails: ["zhangzhenyuan@example.com"],
        phones: ["13600000000"],
        orcid: "0000-0002-2345-6789",
        avatar: "https://example.com/avatar/zhangzhenyuan.jpg",
        position: "研究成员"
    }
];

// 导出数据供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { teamMembers, fundingData };
} else {
    window.teamMembers = teamMembers;
    window.fundingData = fundingData;
}